### ISSUE TITLE
Certain functions cause app to fail uberjar

### ISSUE THREAD

**Issue by coyotespike** [ibdknox/jayq#59]
When packaging a Reagent app into an uberjar, I found that any namespace that used Jayq, or referenced another namespace that used Jayq, failed compilation. I was requiring $, css, and so forth. My project.clj does include Prismatic/dommy and domina. Not sure what dependency issue might have caused this.

**Comment by frankhale** [comment]
Interesting, I was just able to package my app into an uberjar and everything went fine. Can you provide a sample project that reproduces this?

**Comment by coyotespike** [comment]
Yes, here's a minimal project which reproduces the problem: https://github.com/coyotespike/jayq-problem

To be specific about the expected behavior: if you run `lein figwheel`, the default page will appear. However, if you run `lein uberjar`, and then `java -jar target/jayq-problem.jar`, you will instead see the warning text that ClojureScript has not been compiled. In `handler.clj` this warning is returned when `[:div#app]` fails to render. Mystifying!

**Comment by frankhale** [comment]
Thanks!

**Comment by frankhale** [comment]
I tried to run your code but after running lein figwheel and opening the page at 127.0.0.1:3449 it tells me that the Clojurescript hasn't been compiled and to run lein figwheel again. Additionally, if I run lein uberjar and then run the jar like you mentioned and open 127.0.0.1:3000 I get the same message. I've tried multiple times, what is going on? I definitely can see the messages from the compiler stating that the Clojurescript has been compiled.

**Comment by coyotespike** [comment]
Weird, right? Now if you go into core.cljs and comment out the Jayq dependency, as well as the `$interface` function, it should render properly. 
Instead of using Jayq, I just always have things like:
```
(defn switch-buttons [atom default alternative]
  (fn []
    (if @atom
      default
      alternative)))
```
In other words, I leverage React/Reagent.
